### ISSUE TITLE
Passing strings or symbols to the middleware builder is deprecated

### ISSUE THREAD

**Issue by mooktakim** [imajes/rack-heartbeat#7]
This is a minor issue.
Rails 5 seems have deprecated passing in string in the middleware builder.
Getting a warning like this:

```
DEPRECATION WARNING: Passing strings or symbols to the middleware builder is deprecated, please change
them to actual class references.  For example:

  "Rack::Heartbeat" => Rack::Heartbeat

```

**Comment by imajes** [comment]
thanks for the tip. I haven't tested it on Rails 5 yet, and would need to see how this does for backward compatibility... at least it's only a deprec warning!

**Comment by mooktakim** [comment]
I've been using it with beta3, seems to be working fine.

Cheers for creating the gem.

**Comment by olleolleolle** [comment]
I believe this has been fixed, and I just tried using all the examples from the README with a newly-created Rails 5 app. All of it works as advertised!

https://github.com/imajes/rack-heartbeat/blob/master/lib/rack/heartbeat/railtie.rb#L5

**Comment by mooktakim** [comment]
Cool thats great
